{{/* vim: set filetype=mustache: */}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ template "rebuildah.fullname" . }}
  labels: {{- include "rebuildah.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc 
      port: 50051
      protocol: TCP
      targetPort: 50051 
  selector:
    {{- include "rebuildah.matchLabels" . | nindent 4 }}
  type: ClusterIP
